# Generated by Django 3.2.18 on 2023-03-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airportx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='raa',
        ),
    ]
